        suite: 'spades',
        rank: 2,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def:,
        ud_atk: ,
        ud_eft: ,
        quota: ,
        s_atk: ,
        s_def: null,
        s_mod: null, 
      },
      {
        suite: 'spades',
        rank: 3,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 4,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 5,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 6,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 7,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 8,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 9,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 10,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 11,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 12,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },
      {
        suite: 'spades',
        rank: 13,
        prefix: '',
        ud_name: '',
        hp: ,
        type: '',
        ud_def: ,
        ud_atk: ,
        ud_eft: '',
        quota: ,
        s_atk: ,
        s_def: ,
        s_mod: , 
      },